/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as HostRouteImport } from './routes/host'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as StaysIndexRouteImport } from './routes/stays.index'
import { Route as StaysPropertyIdRouteImport } from './routes/stays.$propertyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysIndexRoute = StaysIndexRouteImport.update({
  id: '/stays/',
  path: '/stays/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysPropertyIdRoute = StaysPropertyIdRouteImport.update({
  id: '/stays/$propertyId',
  path: '/stays/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/favourites': typeof FavouritesRoute
  '/host': typeof HostRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/trips': typeof TripsRoute
  '/stays/$propertyId': typeof StaysPropertyIdRoute
  '/stays/': typeof StaysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/favourites': typeof FavouritesRoute
  '/host': typeof HostRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/trips': typeof TripsRoute
  '/stays/$propertyId': typeof StaysPropertyIdRoute
  '/stays': typeof StaysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/favourites': typeof FavouritesRoute
  '/host': typeof HostRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/trips': typeof TripsRoute
  '/stays/$propertyId': typeof StaysPropertyIdRoute
  '/stays/': typeof StaysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/favourites'
    | '/host'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/trips'
    | '/stays/$propertyId'
    | '/stays/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/favourites'
    | '/host'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/trips'
    | '/stays/$propertyId'
    | '/stays'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/favourites'
    | '/host'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/trips'
    | '/stays/$propertyId'
    | '/stays/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  FavouritesRoute: typeof FavouritesRoute
  HostRoute: typeof HostRoute
  MessagesRoute: typeof MessagesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  TermsRoute: typeof TermsRoute
  TripsRoute: typeof TripsRoute
  StaysPropertyIdRoute: typeof StaysPropertyIdRoute
  StaysIndexRoute: typeof StaysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/': {
      id: '/stays/'
      path: '/stays'
      fullPath: '/stays/'
      preLoaderRoute: typeof StaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/$propertyId': {
      id: '/stays/$propertyId'
      path: '/stays/$propertyId'
      fullPath: '/stays/$propertyId'
      preLoaderRoute: typeof StaysPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  FavouritesRoute: FavouritesRoute,
  HostRoute: HostRoute,
  MessagesRoute: MessagesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  TermsRoute: TermsRoute,
  TripsRoute: TripsRoute,
  StaysPropertyIdRoute: StaysPropertyIdRoute,
  StaysIndexRoute: StaysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
