/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaysRouteImport } from './routes/stays'
import { Route as StaysPropertyIdRouteImport } from './routes/stays.$propertyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysRoute = StaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysPropertyIdRoute = StaysPropertyIdRouteImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => StaysRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stays': typeof StaysRouteWithChildren
  '/stays/$propertyId': typeof StaysPropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stays': typeof StaysRouteWithChildren
  '/stays/$propertyId': typeof StaysPropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stays': typeof StaysRouteWithChildren
  '/stays/$propertyId': typeof StaysPropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stays' | '/stays/$propertyId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stays' | '/stays/$propertyId'
  id: '__root__' | '/' | '/stays' | '/stays/$propertyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StaysRoute: typeof StaysRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays': {
      id: '/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof StaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/$propertyId': {
      id: '/stays/$propertyId'
      path: '/$propertyId'
      fullPath: '/stays/$propertyId'
      preLoaderRoute: typeof StaysPropertyIdRouteImport
      parentRoute: typeof StaysRoute
    }
  }
}

interface StaysRouteChildren {
  StaysPropertyIdRoute: typeof StaysPropertyIdRoute
}

const StaysRouteChildren: StaysRouteChildren = {
  StaysPropertyIdRoute: StaysPropertyIdRoute,
}

const StaysRouteWithChildren = StaysRoute._addFileChildren(StaysRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StaysRoute: StaysRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
